data:
    hostname: data
    image: vertisfinance/base
    command: start
    volumes:
        - "../base/config:/opt/config"
        - "/opt/data"
    environment:
        USER_ID: 1000
        USER_NAME: dev

postgres:
    hostname: postgres
    image: vertisfinance/postgres
    command: start
    volumes:
        - "./config:/opt/config"
    volumes_from:
        - data
    environment:
        USER_ID: 5432
        USER_NAME: pg
        PGDATA: /opt/data/postgres
        DB_PASSWORD: 'secret-!noproduction!'
        CONFIG_FILE: /opt/config/postgresql.conf
        HBA_FILE: /opt/config/pg_hba.conf
        SOCKET_DIR: /opt/data/sockets
        LOG_DIR: /opt/data/logs/postgres
        BACKUP_DIR: /opt/data/db_backup
        SEMAPHORE: /opt/data/semaphores/postgres
    ports:
        - "5432:5432"
